### ISSUE TITLE
Error loading feed

### ISSUE THREAD

**Issue by tdm00** [robertkowalski/octopress-coderwall#1]
I'm not able to get the jQuery version working, it just displays "Error loading feed".
If I copy the ender version then everything loads just great.

**Comment by robertkowalski** [comment]
Are you using the 2.1 branch of octopress where jQuery is included?

**Comment by tdm00** [comment]
No, I was using 2.0, thanks I missed that vital detail

On Thu, Mar 7, 2013 at 1:31 PM, Robert Kowalski notifications@github.comwrote:

> Are you using the 2.1 branch of octopress where jQuery is included?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robertkowalski/octopress-coderwall/issues/1#issuecomment-14577774
> .

## 

_Troy Murray_
